### ISSUE TITLE
Missing release package "vagrant/binary-amd64/Packages"

### ISSUE THREAD

**Issue by oroskodias** [ByteInternet/hypernode-vagrant#127]
On February 2nd the [release package](http://ubuntu.byte.nl/dists/precise/Release) list was updated. The new list is missing an entry for "vagrant/binary-amd64/Packages" which causes fatal errors during installation. Following is a screen shot of this error:

<img width="1546" alt="screen shot 2017-02-07 at 8 23 05 am" src="https://cloud.githubusercontent.com/assets/24477165/22692864/ddd083c6-ed0e-11e6-855a-187b62376176.png">

Vagrant 1.9.1
Version 5.0.26
GuestAdditions 5.0.26

**Comment by vdloo** [comment]
Hi, we're currently working on our repos to prepare for an Ubuntu upgrade and it looks like this is a side-effect of that. We removed the vagrant component which used to contain some specific kernel headers that were needed in the past, I'm pretty sure they're not needed anymore. Until we build new images you could either provision the machine without xdebug by putting this in your `local.xml`:

```
xdebug:
  state: false
```

or by destroying the box and entering 'false' in the dialogue when it asks to enable xdebug.

Otherwise if you do need xdebug you could log in to the machine and remove the component manually and run `vagrant provision again`

```
vagrant ssh
sudo su
vim /etc/apt/sources.list.d/ubuntu_byte_nl.list
# remove this line: deb http://ubuntu.byte.nl precise vagrant
```

if you then run `apt-get update` it should not fail with `W: Failed to fetch http://ubuntu.byte.nl/dists/precise/Release  Unable to find expected entry 'vagrant/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)` anymore. After that you can run `vagrant provision` and it should install xdebug normally like before.

**Comment by oroskodias** [comment]
Yep it works pretty good! Thank you!

**Comment by vdloo** [comment]
this should be fixed from vagrant box versions 3697 and up
```
$ vagrant box list | grep virtualbox
hypernode_php5         (virtualbox, 3697)
hypernode_php7         (virtualbox, 3697)
```
