### ISSUE TITLE
pub and symlink?

### ISSUE THREAD

**Issue by reinos** [ByteInternet/hypernode-vagrant#166]
Is the pub folder needed

![image](https://user-images.githubusercontent.com/633730/28416872-0f0635ea-6d56-11e7-9594-dd18e17348b2.png)

and how does symlink working for the box? Can i symlink a folder into the `/data/web` folder?

**Comment by vdloo** [comment]
Hi @reinos, you can set up the box however you want. The /data/web/public directory is the document root (or web root). Nginx and PHP-FPM will serve files from there. Normally for Magento installation is in /data/web/magento and the /data/web/magento/pub directory is symlinked to /data/web/public. This is so that only the files needed to serve the shop are in the document root and nothing more. That's a security best practice in Magento 2. Also see [this comment](https://magento.stackexchange.com/a/98584/35109) on the Magento stackexchange.

**Comment by reinos** [comment]
Ok thanks.
