### ISSUE TITLE
content of /data/web/nginx (it's empty after start)

### ISSUE THREAD

**Issue by mariarti** [ByteInternet/hypernode-vagrant#31]
Have hypernode updated from version '2638' to '2647'
VirtualBox Version 5.0.14 r105127
vagrant version 1.8.1
CentOS release 6.7 (Final) x64

Issue:
After started box nothing appears in ./hypernode-vagrant/data/web/nginx , i.e. config/s does not appear
or I should something write by myself? 
If so - what should contain that folder?

Thanks in advance.

**Comment by vdloo** [comment]
/data/web/nginx is empty because the data/web/nginx of the repo is mounted over it
```
config.vm.synced_folder "data/web/nginx/", "/data/web/nginx/", owner: "app", group: "app", create: true
```
this is done so that the configs persist if the box is destroyed. You could temporarily unmount the shared folder to access the default files, copy those somewhere else and then remount the shared dir and copy the files back.

```
~/code/projects/hypernode-vagrant vagrant ssh
vagrant@beb7b8-projects-magweb-vgr:~$ sudo su
root@beb7b8-projects-magweb-vgr /home/vagrant # umount /data/web/nginx
root@beb7b8-projects-magweb-vgr /data # su app -c 'mkdir -p /data/web/nginx_temp; cp /data/web/nginx/* /data/web/nginx_temp'
```

then stop and start the box to have the folders remounted (you could also do it [manually](https://help.ubuntu.com/community/VirtualBox/SharedFolders) with ```mount -t vboxsf ...``` but by letting vagrant handle it you don't have to mess with the permissions).

```
~/code/projects/hypernode-vagrant vagrant halt
~/code/projects/hypernode-vagrant vagrant up
...
==> hypernode: Mounting shared folders...
    hypernode: /vagrant => /home/vdloo/code/projects/hypernode-vagrant
    hypernode: /data/web/nginx => /home/vdloo/code/projects/hypernode-vagrant/data/web/nginx
    hypernode: /data/web/public => /home/vdloo/code/projects/hypernode-vagrant/data/web/public
...
```

and finally log back in as app and move the default files to the shared nginx dir
```
app@beb7b8-projects-magweb-vgr:/home/vagrant$ mv /data/web/nginx_temp/* /data/web/nginx/
```

If you log back out again you will see that the files are now in the data/web/nginx dir on the host
```
~/code/projects/hypernode-vagrant/data/web/nginx ls
handler.conf  http.magerunmaps  magmi.conf  server.basicauth  server.blacklist  server.rewrites
```

**Comment by mariarti** [comment]
Thanks, it works. 

p.s.
Which service or app parse server.* and http.* conf's to nginx?

**Comment by vdloo** [comment]
That's the nginx-config-reloader

```
app@beb7b8-projects-magweb-vgr:~$ service nginx-config-reloader status
 * nginx_config_reloader is running
```

This might also help: https://github.com/ByteInternet/hypernode-vagrant#the-config-reloader-is-not-reloading-on-changes-in-datawebnginx

**Comment by vdloo** [comment]
The synced nginx dir is now populated during provisioning https://github.com/ByteInternet/hypernode-vagrant/pull/35
