### ISSUE TITLE
Using $developermode

### ISSUE THREAD

**Issue by hongaar** [ByteInternet/hypernode-vagrant#59]
I noticed there's a variable `$developermode` in the file `/etc/nginx/handlers.conf` but can't seem to get it to work. Is this feature supported, and if so, how do I enable this? Thanks!

![image](https://cloud.githubusercontent.com/assets/205834/14114316/c77ff9d8-f5d6-11e5-83f0-f08a869363be.png)

**Comment by Cieper** [comment]
You can turn on `$developermode` / `MAGE_IS_DEVELOPER_MODE` the same way you can set your `$storecode`:
If you place the following block in your http context (i.e.: ~/nginx/http.magerunmaps, or ~/nginx/http.developermode), you can turn on and off developermode on a per IP basis.

```
map $remote_addr $developermode {
  default "";
  10.0.3.1 1;
}
```

The `10.0.3.1` IP used above is the default IP used in vagrant for your own PC. If it doesn't work, check the `/var/log/nginx/access.log` file to see if you have the right IP, or `~/nginx/nginx_error_output` for any errors made in the config file.

**Comment by hongaar** [comment]
Thanks a bunch! Bonus question: is it also possible to somehow always set $developermode to `1` in the staging environment?

**Comment by Cieper** [comment]
I don't think you can easily do so, I'm afraid. The PHP handlers and its settings are defined in the http context, and the only way to do staging specific settings is by doing so in the server context. 

You can give it a try using a `~/nginx/staging.developermode` file, but you might have to end setting the value in PHP code instead.

**Comment by tomlankhorst** [comment]
On my box 3066 the $developermode map seems to have no effect. A dump of $_SERVER does not show the MAGE_IS_DEVELOPER key even when I set the default value for $developermode to 1. The store code and type are appearing though. Have restarted the nginx server. Varnish has caching disabled. Anyone experience with this?

**Comment by vdloo** [comment]
check `/var/log/nginx` for errors in your nginx config files. the nginx_config_reloader validates the configs in /data/web/nginx first before copying them to /etc/nginx/app. for example I used a set while that is not possible in that context:

```
root@beb7b8-projects-magweb-vgr /var/log/nginx # tail -f error.log 
2016/07/08 12:05:49 [emerg] 7000#7000: "set" directive is not allowed here in /etc/nginx/app/http.magerunmaps:23
```

If there is an error the settings will not be copied to the nginx config dir. You shouldn't need to restart or reload nginx because whenever a file changes in the /data/web/nginx dir it automatically triggers the reloader.

Also make sure you got the IP right if you want to do it on a by IP basis like @Cieper mentioned. You can check by enabling it for all IPs first. 

```
map $remote_addr $developermode {
  default true;
}
```

also make sure the nginx_config_reloader is still running (it should always be)
```
app@beb7b8-projects-magweb-vgr:~$ ps aux | grep nginx_config_reloader
root      7622  0.4  0.5  52936 10996 ?        Ss   12:16   0:00 /usr/bin/python /usr/bin/nginx_config_reloader --monitor
```
if for some reason it's not I recommend you destroy your box and `vagrant box update` to the latest version and git pull the hypernode-vagrant repo to make sure you are up to date and try again

**Comment by tomlankhorst** [comment]
Thanks @vdloo, the `/var/log/nginx/error.log` is almost empty (one irrelevant connection refused entry). The `nginx-config-reloaded` is running. I once hear that there was some difficulty in using the reloader with the virtualbox synchornisation mechanism that causes config not to update when files were changed. I looked in the `/etc/nginx/app` folder and it seemed that the config was not copied. I copied it manually which worked. As the root user I restarted `nginx-config-reloaded` and changed a config file. This seems to fix the problem. 

`vagrant ssh`
`sudo service nginx-config-reloader restart`

**Comment by hongaar** [comment]
I have a set of bootstrap scripts on my box, some of which modify/symlink some nginx config files, which then don't get picked up as changed by the config reloader, so I run these lines after bootstrap is done:

```sh
#!/bin/bash

# Force refresh of nginx configuration
touch "$HOME/nginx/server.trigger_reload"
sleep 0.5
rm -f "$HOME/nginx/server.trigger_reload"
```
