### ISSUE TITLE
Readme should include the varnish key

### ISSUE THREAD

**Issue by janw-oostendorp** [ByteInternet/hypernode-vagrant#70]
The turpentine [docs](https://github.com/nexcess/magento-turpentine/wiki/FAQ#i-added-the-varnish-secret-key-but-turpentine-still-cant-talk-to-varnish) mentions the solution.

**Comment by vdloo** [comment]
@frosit added this and other settings to the default index.php. Now if you boot a hypernode-vagrant box and access the webserver you are presented with some of the settings you would otherwise find in the Byte servicepanel:

![info](https://cloud.githubusercontent.com/assets/1437341/16147925/9e09ebf6-3486-11e6-87aa-e5685316dfe5.png)

**Comment by janw-oostendorp** [comment]
nice
